# Generated by Django 4.1.6 on 2023-02-09 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='list_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 9, 18, 39, 11, 478688, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
