# Generated by Django 4.1.6 on 2023-02-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_current_bid_listing_start_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='num_bids',
            field=models.IntegerField(default=0),
        ),
    ]
