# Generated by Django 4.1.6 on 2023-02-24 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='start_bid',
            new_name='current_bid',
        ),
    ]
